### ISSUE TITLE
Add 'download' button for the according pdf file inside antora ui

### ISSUE THREAD

**Issue by zrgt** [admin-shell-io/aas-specs-antora#15]
Aadd a button for downloading PDF in ui. E.g. some download Button near "snapshot".

See #10

**Comment by monsieuremre** [comment]
Completed with https://github.com/admin-shell-io/aas-specs-antora-ui/commit/addcfa33134cdac9a3e954df7d9100961e3f9164

**Comment by monsieuremre** [comment]
The download button uses javascript to get the current url. Then depending on the current url, it determines whether we are on part 1, part 2, part 3a, part 5 or the main page. After determining it, the download button downloads the relevant pdf file, depending on the current page. So when viewing part 3a, clicking download will download the pdf for 3a. If clicked whilst viewing part 5, the pdf file of part 5 is downloaded.

**Comment by zrgt** [comment]
Here are issues, I've found in the solution:

- [ ] The download button should be next to the "Edit the page" link. 

- [ ] It should be set to "Download PDF"

- [ ] It is very bad decision to hard-code the links/names of pdf files. It will be the issue each time a new Specification part is added. So Links have to be somehow provided automatically in antora-ui.

**Comment by monsieuremre** [comment]
> The name of link schoud be "Download PDF"

This is quite trivial to fix. Will be done.

>  The download button should be next to the "Edit the page" link.

I see. So it won't be in the header thing, but rather in that thing under it. I think this should be easily possible too. Will do with the other one.

>  It is a bad decision to hard-code the links/names of pdf files. It will be the issue each time a new Specification part is added. So Links have to be somehow provided automatically in antora-ui. We can either set the same name to all generated pdfs or set it depending on the documentation part name, such that we can regenerate the name in antora-ui

This is a blocker. I have tested with several ways before arriving to this solution. This one avoids all kinds of hard coding of urls, names and links. The component versions and names can change, including titles etc.

The only thing that is hard-coded is the pdf name, which has to be determined before the fact. The pdf files have predictable names, they don't change. It is the name of the module, declared in the .yml file. (unless overridden in nav.adoc)

So the entire url is dynamic, it generates on the content. Only the pdf name is static. Which it has to be. The antora module name is an asciidoc property (or antora rather). It is not a property in the html file. There is no reliable way to extract the pdf name, because the script cannot know the antora module title. Because it is not in the webpage, it is in the source files that generates the html files.

So you are right, it would be more ideal to find a way to get the name of the pdf file dynamically. But it also brings more complications. There is no way to extract the module title with javascript. I presume, if we use node.js, we could read the files serverside and just pick the pdf file that is in the same directory as the html file. This is rather unnecessarily complex tho.

There is a better way to achieve what you want that I could think of right now. If in the source repositories, the .yml files that provide the module information declare that the module's name and title are the same, or the name is just the title but all small case and dashed in place of spaces, then we can easily and reliably get the name of the pdf file from the url.

I can modify the javascript code for this. Only think that would be required is, the module names will be reformatted.

Here are the steps. Let's take Part 2 as an example. The file under the path https://github.com/admin-shell-io/aas-specs-api/blob/IDTA-01002-3-1_preparation/documentation/IDTA-01002-3/antora.yml need to reformatted from

```
name: IDTA-01002-3
title: 'Part 2: API'
```

to

```
name: part-2-api
title: 'Part 2: API'
```

This would not only make the url's more readable and user friendly, it would also make it very trivial the extract the pdf name from the url.

If we do not choose this solution, as I said, it would have to involve more complicated tools like node.js.

**Comment by zrgt** [comment]
Also there is an issue, that generated links in the current solution are sometimes wrong, e.g. here:
https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/Spec/IDTA-01001_Metamodel_Core.html

Please take a look here: https://docs.antora.org/antora-ui-default/templates/ May be there are some variables, which might help. 

There is definitely a solution to generate download links, without setting the same name and title. E.g. we can set the name of generated PDF to the module's name.

**Comment by monsieuremre** [comment]
links are now completely dynamic. see https://github.com/admin-shell-io/aas-specs-antora-ui/commits/v0.4.1/
